/* eslint-disable @next/next/no-page-custom-font */
import type { NextPage } from "next";
import Head from "next/head";

import SignIn from "./SignIn/SignIn";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lobster&family=Roboto:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <title>Todo nineBox</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <SignIn />
    </>
  );
};

export default Home;
